/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.15
 * Generated at: 2014-12-08 13:56:36 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class AccountCreationView_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.1//FR\" \"http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd\">\n");
      out.write("<html xmlns=\"http://www.w3.org/1999/xhtml\"> \n");
      out.write(" <head>\n");
      out.write("  <title>Cr&#233ation d'un compte</title>\n");
      out.write("  <link rel=\"stylesheet\" type=\"text/css\" media=\"all\" href=\"css/style.css\" />\n");
      out.write(" </head>\n");
      out.write(" <body>\n");
      out.write("  \n");
      out.write("   ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../html/header.html", out, false);
      out.write("\n");
      out.write("   ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "menu.jsp", out, false);
      out.write("\n");
      out.write("   <div class=\"main\">\n");
      out.write("     ");

   	Object data = request.getAttribute("data");

	if(data!=null && data instanceof String){
	out.println(data);
	}
     
      out.write("\n");
      out.write("\t\n");
      out.write("\t<br />Veuillez remplir les formulaire ci-dessous afin de cr&#233er un compte sur MusicOnline.<br /> <br />\n");
      out.write("\t\t<fieldset> \n");
      out.write("\t\t\t<legend>Cr&#233ation de compte</legend>\n");
      out.write("\t\t\t<form method=\"POST\" action=\"?p=validcpt\" enctype=\"application/x-www-form-urlencoded\">\n");
      out.write("\t\t\t\t<table>\n");
      out.write("\t\t\t\t   <tr>\n");
      out.write("\t\t\t\t       <td>Nom :</th>\n");
      out.write("\t\t\t\t       <td><INPUT  type=\"text\" name=\"nom\"/></th>\n");
      out.write("\t\t\t\t   </tr>\n");
      out.write("\t\t\t\t   <tr>\n");
      out.write("\t\t\t\t       <td>Pr&#233nom :</td>\n");
      out.write("\t\t\t\t       <td><INPUT type=\"text\" name=\"prenom\"></td>\n");
      out.write("\t\t\t\t   </tr>\n");
      out.write("\t\t\t\t   <tr>\n");
      out.write("\t\t\t\t       <td>Login :</th>\n");
      out.write("\t\t\t\t       <td><INPUT  type=\"text\" name=\"login\"/></th>\n");
      out.write("\t\t\t\t   </tr>\n");
      out.write("\n");
      out.write("\t\t\t\t   <tr>\n");
      out.write("\t\t\t\t       <td>Mot de passe :</td>\n");
      out.write("\t\t\t\t       <td><INPUT type=\"text\" name=\"password\"></td>\n");
      out.write("\t\t\t\t   </tr>\n");
      out.write("\t\t\t\t   <tr>\n");
      out.write("\t\t\t\t       <td>Date de naissance (AAAA-MM-JJ) :</th>\n");
      out.write("\t\t\t\t       <td><INPUT  type=\"text\" name=\"date\"/></th>\n");
      out.write("\t\t\t\t   </tr>\n");
      out.write("\n");
      out.write("\t\t\t\t   <tr>\n");
      out.write("\t\t\t\t       <td>Adresse e-mail :</td>\n");
      out.write("\t\t\t\t       <td><INPUT type=\"text\" name=\"email\"></td>\n");
      out.write("\t\t\t\t   </tr>\n");
      out.write("\t\t\t\t   <tr>\n");
      out.write("\t\t\t\t       <td>Adresse (lieu-dit, rue, ...) :</th>\n");
      out.write("\t\t\t\t       <td><INPUT  type=\"text\" name=\"adresse\"/></th>\n");
      out.write("\t\t\t\t   </tr>\n");
      out.write("\n");
      out.write("\t\t\t\t   <tr>\n");
      out.write("\t\t\t\t       <td>Code postal :</td>\n");
      out.write("\t\t\t\t       <td><INPUT type=\"text\" name=\"code\"></td>\n");
      out.write("\t\t\t\t   </tr>\n");
      out.write("\t\t\t\t   <tr>\n");
      out.write("\t\t\t\t       <td>Ville :</th>\n");
      out.write("\t\t\t\t       <td><INPUT  type=\"text\" name=\"ville\"/></th>\n");
      out.write("\t\t\t\t   </tr>\n");
      out.write("\n");
      out.write("\t\t\t\t   <tr>\n");
      out.write("\t\t\t\t       <td>Pays :</td>\n");
      out.write("\t\t\t\t       <td><INPUT type=\"text\" name=\"pays\"></td>\n");
      out.write("\t\t\t\t   </tr>\n");
      out.write("\n");
      out.write("\t\t\t\t</table>\n");
      out.write("\t\t\t\t<br/><INPUT type=\"submit\" name=\"confirmer\" value=\"Confirmer\"/>\n");
      out.write("\t\t\t</form>\n");
      out.write("\t\t</fieldset>\n");
      out.write("   </div>\n");
      out.write(" </body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
